[theme]

# Primary accent for interactive elements
primaryColor = '#636c81'

# Background color for the main content area
backgroundColor = "#35455c"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#898EA2"

# Color used for almost all text
textColor = "#ffffff"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


